### ISSUE TITLE
question 認証コードのシード値が取得できない。

### ISSUE THREAD

**Issue by nusu-github** [Nkyoku/voiceroid_daemon#1]
起動中のVOICEROID2エディタから取得となっていますがどんなに頑張っても取得できません。
試した方法
c直下での起動
管理者権限での起動
先にvoiceroid_daemon起動してからVOICEROID2エディタ起動(またはその逆)
IEから取得(最新版)
chromeから取得(最新版)
firefoxから取得(最新版)
再ダウンロード
.NET Core 3.1のx84x64インストール
.NET Framework 4.8のインストール

ソースコードからのビルドは不可能でした。
どのようにすれば取得できますか？

**Comment by nusu-github** [comment]
P.S.
aitalk_wrapperの「認証コードのシード値」を入れたら問題なく成功しました。
ですがやはり起動中のVOICEROID2エディタから取得はできませんでした。

**Comment by Nkyoku** [comment]
問題が起きそうな箇所を修正してv2.0.1としてアップロードしました。
該当箇所は認証コードを取得するためのInjector.exeにVOICEROID2エディタのパスを与える部分です。
これで動けばいいのですが。

このプログラムは古い.NET Core 2.1を使っています。
ビルドとデバッグに必要なSDKとASP.NET Core Runtimeは現在も下記リンクから入手可能です。
https://dotnet.microsoft.com/download/dotnet-core/2.1
しかしプロジェクトの設定から「対象のフレームワーク」を変更すれば.NET Core 3系でもビルド可能かもしれません。

**Comment by nusu-github** [comment]
ありがとうございます。
無事動作しました。
